apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: msa
spec:
  type: LoadBalancer
#  type: ClusterIP # 인그레스 전용
#  type: NodePort
  selector:
    app: demo-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
#      nodePort: 30080
